### ISSUE TITLE
loading package crashes R 

### ISSUE THREAD

**Issue by aakarner** [walkerke/crsuggest#10]
Executing `library(crsuggest)` as the first command in the terminal consistently crashes both RStudio and the base R gui. In RStudio I get "R Session Aborted." The R gui just closes without posting an error.

I'm on Windows 10, have updated to the latest R version (4.2.1) and updated all `crsuggest` dependencies.

**Comment by walkerke** [comment]
Hmm - I can't reproduce this, but I'll be able to test on a Windows machine on Monday.  I'll let you know if I figure anything out.

**Comment by walkerke** [comment]
I just tested on my Windows machine and it worked fine.  Unfortunately, I'm not quite sure what the problem could be.  I'll leave the issue open in case someone else in the community has encountered this issue and can help.
